name: Deploying application based on environment

on:
  workflow_dispatch:

jobs:
  env_deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - dev
          - qa
          - prod
        include:
          - environment: dev
            app_url: dev.dim.com
          - environment: qa
            app_url: qa.dim.com
          - environment: prod
            app_url: prod.dim.com

    # Select GitHub Environment dynamically
    environment:
      name: ${{ matrix.environment }}

    steps:
      - name: Deployment to different environment
        run: |
          echo "Environment: ${{ matrix.environment }}"
          echo "Application URL: ${{ matrix.app_url }}"
          echo "Deploying application to ${{ secret.API_KEY }}"

          echo "API Key is available for deployment"
